version: "3.8"
services:
  api_service:
    build: ./
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: customerDatabase
      MYSQL_USER: martin82
      MYSQL_PASSWORD: password82
      MYSQL_ROOT_PASSWORD: password82