spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/customerDatabase
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  enabled: true

---

spring:
  config:
    activate:
      on-profile: default
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: myDatabase
  enabled: true

---

spring-test:
  vehicles:
    maxNoOfVehicles: 20
    enabled: true
  customers:
    maxNoOfCustomers: 20
    enabled: true



